apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  annotations:
    volume.data.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage