---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  namespace: myns
  labels:
    name: nwapp-cm
data:
  DB_USER: root
  DB_HOST: mydb-svc.myns.svc.cluster.local
  
---
apiVersion: v1
kind: Secret
metadata:
  name: nwapp-secret
  namespace: myns
data:
  DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  namespace: myns
  labels:
    name: nwapp-deploy
    version: "v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nwapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nwapp-pod
      labels:
        name: nwapp-pod
    spec:
      containers:
      - name: nwapp-container
        image: stackupiss/northwind-app:v1
        imagePullPolicy: Always
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef: 
              fieldPath: status.podIP
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwdb-secret
              key: MYSQL_ROOT_PASSWORD
        envFrom:
        - configMapRef:
            name: nwapp-cm
        ports:
        - name: nwapp-http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ready
            port: nwapp-http
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: nwapp-http
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myns
  labels:
    name: myapp-svc
spec:
  type: LoadBalancer
  selector:
    name: nwapp-pod
  ports:
  - name: myappsvc-http
    port: 80
    targetPort: nwapp-http